# Generated by Django 5.1 on 2024-08-30 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perperiodo', models.CharField(blank=True, max_length=50, null=True)),
                ('acta', models.CharField(max_length=30)),
                ('facultad', models.CharField(choices=[('INGENIERÍA Y TECNOLOGÍA', 'Ingeniería y Tecnología'), ('mas..', 'mas..')], default='INGENIERÍA Y TECNOLOGÍA', max_length=100)),
                ('carrera', models.CharField(choices=[('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'), ('mas..', 'mas..')], default='INGENIERÍA DE SISTEMAS', max_length=100)),
                ('titulo', models.CharField(max_length=450)),
                ('lugar', models.CharField(max_length=50)),
                ('fechadefensa', models.DateField(default=django.utils.timezone.now)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('resultado', models.CharField(choices=[('Suficiente', 'Suficiente'), ('Insuficiente', 'Insuficiente'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Postergado', 'Postergado')], default='Suficiente', max_length=15)),
                ('observacion_1', models.TextField(max_length=200)),
                ('observacion_2', models.TextField(max_length=200)),
                ('observacion_3', models.TextField(max_length=200)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base Actas',
                'verbose_name_plural': 'Actas Base General',
            },
        ),
        migrations.CreateModel(
            name='HabilitarSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitarInv', models.BooleanField(default=True, verbose_name='Habilitar Formulario')),
            ],
            options={
                'verbose_name': 'Habilitar Inv',
                'verbose_name_plural': 'Habilitacion Inv',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='ActaPrivada',
            fields=[
                ('actageneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seg_mod_graduacion.actageneral')),
                ('calificacion1', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Acta Privada',
                'verbose_name_plural': 'Actas defensa Privada',
            },
            bases=('seg_mod_graduacion.actageneral',),
        ),
        migrations.CreateModel(
            name='ActaProyectoPerfil',
            fields=[
                ('actageneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seg_mod_graduacion.actageneral')),
            ],
            options={
                'verbose_name': 'Acta Perfil',
                'verbose_name_plural': 'Actas Defensa Perfiles',
            },
            bases=('seg_mod_graduacion.actageneral',),
        ),
        migrations.CreateModel(
            name='InvCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invtitulo', models.CharField(max_length=450, verbose_name='Agregar Titulo')),
                ('slug', models.SlugField(unique=True)),
                ('invfecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('invdescripcion', models.TextField(blank=True, verbose_name='Agregar una Descripcion Breve')),
                ('invdocumentacion', models.FileField(blank=True, null=True, upload_to='documento/investigacion', verbose_name='Agregar Documentacion')),
                ('investado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
            options={
                'verbose_name': 'Investigacion cientifica',
                'verbose_name_plural': 'Investicaciones cientificas',
            },
        ),
        migrations.CreateModel(
            name='ComentarioInvCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invcomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('invfecha_post', models.DateTimeField(auto_now_add=True)),
                ('invdocorregido', models.FileField(blank=True, null=True, upload_to='documento/investigacion', verbose_name='Agregar Documentacion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.invcientifica')),
            ],
            options={
                'verbose_name': 'Comentario Inv',
                'verbose_name_plural': 'Comentario InvCientifica',
                'ordering': ['-invfecha_post'],
            },
        ),
        migrations.CreateModel(
            name='HabilitarProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_tutor', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
            ],
            options={
                'verbose_name': 'Habilitar Proyecto Final',
                'verbose_name_plural': 'Habilitar Proyectos Final',
            },
        ),
        migrations.AddField(
            model_name='actageneral',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad'),
        ),
        migrations.CreateModel(
            name='PerfilProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertitulo', models.CharField(max_length=450, verbose_name='Agregar Titulo Perfil')),
                ('slug', models.SlugField(unique=True)),
                ('perfecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perdescripcion', models.TextField(blank=True, verbose_name='Agregar una Descripcion')),
                ('perdocumentacion', models.FileField(blank=True, null=True, upload_to='documento/perfil', verbose_name='Agregar Documentacion')),
                ('perestado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('permodalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
            options={
                'verbose_name': 'Perfil Proyecto',
                'verbose_name_plural': 'Perfil de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ComentarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('perfecha_post', models.DateTimeField(auto_now_add=True)),
                ('perdocorregido', models.FileField(blank=True, null=True, upload_to='documento/perfil', verbose_name='Agregar Documentacion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='seg_mod_graduacion.perfilproyecto')),
            ],
            options={
                'verbose_name': 'Comentario Perfil',
                'verbose_name_plural': 'Comentario Perfiles',
                'ordering': ['-perfecha_post'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitada', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=450)),
                ('resumen', models.TextField(max_length=500)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('guia_externo', models.CharField(default='Ninguno', max_length=250)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documento/proyectofinal', verbose_name='Agregar Documentacion')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('jurado_1_aprobado', models.BooleanField(default=False)),
                ('jurado_2_aprobado', models.BooleanField(default=False)),
                ('jurado_3_aprobado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto Final',
                'verbose_name_plural': 'Proyectos Finales',
            },
        ),
        migrations.CreateModel(
            name='ComentarioProFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actcomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('actfecha_post', models.DateTimeField(auto_now_add=True)),
                ('actdocorregido', models.FileField(blank=True, null=True, upload_to='documento/proyectofinal', verbose_name='Agregar Documentacion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('actproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='seg_mod_graduacion.proyectofinal')),
            ],
            options={
                'verbose_name': 'Comentario Proyecto Final',
                'verbose_name_plural': 'Comentarios Proyecto Final',
                'ordering': ['-actfecha_post'],
            },
        ),
        migrations.CreateModel(
            name='RepositorioTitulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitada', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=450)),
                ('resumen', models.TextField(max_length=500)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('guia_externo', models.CharField(max_length=250)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documento/repositorios', verbose_name='Agregar Documentacion')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('jurado_1_aprobado', models.BooleanField(default=False)),
                ('jurado_2_aprobado', models.BooleanField(default=False)),
                ('jurado_3_aprobado', models.BooleanField(default=False)),
                ('periodo', models.CharField(max_length=50)),
                ('anio_egreso', models.IntegerField()),
                ('numero_acta', models.CharField(max_length=50)),
                ('nota_aprobacion', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_estudiante', to=settings.AUTH_USER_MODEL)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_1', to=settings.AUTH_USER_MODEL)),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_2', to=settings.AUTH_USER_MODEL)),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_3', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repositorio',
                'verbose_name_plural': 'Repositorio de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ActaPublica',
            fields=[
                ('actageneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seg_mod_graduacion.actageneral')),
                ('calificacion1', models.IntegerField()),
                ('calificacion2', models.IntegerField()),
                ('notatotal', models.IntegerField()),
                ('presidenteacta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_presidente_Asig', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta Publica',
                'verbose_name_plural': 'Actas Defensa Publica',
            },
            bases=('seg_mod_graduacion.actageneral',),
        ),
    ]
