# Generated by Django 5.1 on 2024-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcientifica',
            name='invdescripcion',
            field=models.TextField(blank=True, verbose_name='Agregar una Descripción Breve'),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='invdocumentacion',
            field=models.FileField(blank=True, null=True, upload_to='documento/investigacion', verbose_name='Agregar Documentación'),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='invtitulo',
            field=models.CharField(max_length=450, verbose_name='Agregar Título'),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='perdescripcion',
            field=models.TextField(blank=True, verbose_name='Agregar una Descripción'),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='perdocumentacion',
            field=models.FileField(blank=True, null=True, upload_to='documento/perfil', verbose_name='Agregar Documentación'),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='pertitulo',
            field=models.CharField(max_length=450, verbose_name='Agregar Título Perfil'),
        ),
    ]
