# Generated by Django 5.1 on 2024-09-19 14:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0002_alter_invcientifica_invdescripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcientifica',
            name='invdocumentacion',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Agregar Documentación'),
        ),
    ]
