# Generated by Django 5.1 on 2024-09-22 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0003_alter_invcientifica_invdocumentacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcientifica',
            name='invdocumentacion',
            field=models.FileField(blank=True, null=True, upload_to='documento/investigacion', verbose_name='Agregar Documentacion'),
        ),
        migrations.CreateModel(
            name='logica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invtitulo', models.CharField(max_length=450, verbose_name='Agregar Título')),
                ('slug', models.SlugField(unique=True)),
                ('invfecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('invdescripcion', models.TextField(blank=True, verbose_name='Agregar una Descripción Breve')),
                ('invdocumentacion', models.FileField(blank=True, null=True, upload_to='documento/investigacion', verbose_name='Agregar Documentacion')),
                ('investado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('habilitar_usuarios_extra', models.BooleanField(default=False, verbose_name='Habilitar más usuarios')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios relacionados')),
            ],
            options={
                'verbose_name': 'Investigación científica',
                'verbose_name_plural': 'Investigaciones científicas',
            },
        ),
    ]
