# Generated by Django 5.1 on 2024-09-22 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0005_logica_user_logica_usersdos_remove_logica_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logica',
            options={'verbose_name': 'logica', 'verbose_name_plural': 'logicas'},
        ),
        migrations.AddField(
            model_name='invcientifica',
            name='habilitar_users',
            field=models.BooleanField(default=False, verbose_name='Habilitar más usuarios'),
        ),
        migrations.AddField(
            model_name='invcientifica',
            name='user_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_userdos', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios relacionados'),
        ),
        migrations.AddField(
            model_name='invcientifica',
            name='user_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_useruno', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios relacionados'),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado'),
        ),
    ]
