# Generated by Django 5.1 on 2024-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0008_perfilproyecto_user_dos_perfilproyecto_user_uno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilproyecto',
            name='habilitar_users',
            field=models.BooleanField(default=False, verbose_name='¡Si el proyecto consta mas de un participante click aqui!'),
        ),
    ]
