# Generated by Django 5.1 on 2024-09-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0010_actageneral_estudiante_dos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actageneral',
            name='habilitar_users',
        ),
    ]
