# Generated by Django 5.1 on 2024-09-25 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0011_remove_actageneral_habilitar_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitarproyectofinal',
            name='estudiante_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_estudiante_dos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AddField(
            model_name='habilitarproyectofinal',
            name='estudiante_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_estudiante_uno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AddField(
            model_name='habilitarproyectofinal',
            name='habilitar_users',
            field=models.BooleanField(default=False, verbose_name='¡Si el proyecto consta mas de un participante click aqui!'),
        ),
    ]
