# Generated by Django 5.1 on 2024-09-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0012_habilitarproyectofinal_estudiante_dos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilitarproyectofinal',
            name='habilitar_users',
        ),
    ]
