# Generated by Django 5.1 on 2024-09-25 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0013_remove_habilitarproyectofinal_habilitar_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectofinal',
            name='estudiante_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_estudiante_dos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AddField(
            model_name='proyectofinal',
            name='estudiante_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_estudiante_uno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AddField(
            model_name='repositoriotitulados',
            name='estudiante_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_estudiante_dos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AddField(
            model_name='repositoriotitulados',
            name='estudiante_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_estudiante_uno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
    ]
