# Generated by Django 5.1 on 2024-10-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0015_carrera_facultad_gestion_remove_actageneral_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.carrera'),
        ),
    ]
