# Generated by Django 5.1 on 2024-10-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0016_alter_estudiante_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
    ]
