# Generated by Django 5.1 on 2024-10-02 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0018_alter_docente_dni_alter_estudiante_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actageneral',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actageneral',
            name='estudiante_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acta_estudiantedos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AlterField(
            model_name='actageneral',
            name='estudiante_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acta_estudianteuno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AlterField(
            model_name='actageneral',
            name='jurado_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_jurado_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actageneral',
            name='jurado_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_jurado_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actageneral',
            name='jurado_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_jurado_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actageneral',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actapublica',
            name='presidenteacta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_presidente_Asig', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentarioinvcientifica',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentarioperfil',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentarioprofinal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habilitarproyectofinal',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habilitarproyectofinal',
            name='estudiante_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_estudiante_dos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AlterField(
            model_name='habilitarproyectofinal',
            name='estudiante_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_estudiante_uno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AlterField(
            model_name='habilitarproyectofinal',
            name='jurado_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habilitarproyectofinal',
            name='jurado_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habilitarproyectofinal',
            name='jurado_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_jurado_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habilitarproyectofinal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado'),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='user_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_userdos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='user_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_useruno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_name_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado'),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='user_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_name_userdos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='user_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_name_useruno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='estudiante_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_estudiante_dos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='estudiante_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_estudiante_uno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='jurado_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='jurado_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='jurado_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_jurado_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='estudiante_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_estudiante_dos', to=settings.AUTH_USER_MODEL, verbose_name='Tercer participante'),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='estudiante_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_estudiante_uno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante'),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='jurado_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='jurado_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='jurado_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_jurado_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
