# Generated by Django 5.1 on 2024-10-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0019_alter_actageneral_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-numero', '-gestion__anio']},
        ),
    ]
