# Generated by Django 5.1 on 2024-10-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0020_alter_periodo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={},
        ),
    ]
