# Generated by Django 5.1 on 2024-10-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0022_alter_periodo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoriotitulados',
            name='anio_egreso',
        ),
    ]
