# Generated by Django 5.1 on 2024-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0023_remove_repositoriotitulados_anio_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcientifica',
            name='habilitar_users',
            field=models.BooleanField(default=False, verbose_name='¡Mas de un Estudiante click aqui!'),
        ),
    ]
