# Generated by Django 5.1 on 2024-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0026_alter_comentarioprofinal_actdocorregido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Ru',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
