# Generated by Django 5.1 on 2024-10-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0027_remove_estudiante_carrera_estudiante_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcientifica',
            name='investado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Preapro', 'Preapro')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='perestado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Preapro', 'Preapro')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Preapro', 'Preapro')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Preapro', 'Preapro')], default='Pendiente', max_length=10),
        ),
    ]
