# Generated by Django 5.1 on 2024-10-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0028_alter_invcientifica_investado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actageneral',
            name='carrera',
            field=models.ForeignKey(default='Ingeniría de Sistemas', on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.carrera'),
        ),
        migrations.AlterField(
            model_name='actageneral',
            name='resultado',
            field=models.CharField(choices=[('Suficiente', 'Suficiente'), ('Insuficiente', 'Insuficiente'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Postergado', 'Postergado')], default='Insuficiente', max_length=15),
        ),
        migrations.CreateModel(
            name='HabilitarTribunalesPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertitulo', models.CharField(max_length=450, verbose_name='Agregar Título Acta')),
                ('perestado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Preapro', 'Preapro')], default='Pendiente', max_length=10)),
                ('jurado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitar_jurado_1', to=settings.AUTH_USER_MODEL, verbose_name='Jurado 1')),
                ('jurado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitar_jurado_2', to=settings.AUTH_USER_MODEL, verbose_name='Jurado 2')),
                ('jurado_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitar_jurado_3', to=settings.AUTH_USER_MODEL, verbose_name='Jurado 3')),
                ('permodalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitar_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitar_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
                ('user_uno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitar_user_uno', to=settings.AUTH_USER_MODEL, verbose_name='Segundo participante')),
            ],
        ),
    ]
