# Generated by Django 5.1 on 2024-10-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0029_alter_actageneral_carrera_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilitartribunalesperfil',
            options={'verbose_name': 'Habilitar Tribunal Perfil', 'verbose_name_plural': 'Habilitar Tribunales Perfil'},
        ),
        migrations.RemoveField(
            model_name='habilitartribunalesperfil',
            name='perestado',
        ),
    ]
