# Generated by Django 5.1 on 2024-10-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0030_alter_habilitartribunalesperfil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actageneral',
            name='acta',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invcientifica',
            name='investado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Proceso', 'Proceso')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilproyecto',
            name='perestado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Proceso', 'Proceso')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='proyectofinal',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Proceso', 'Proceso')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='repositoriotitulados',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Proceso', 'Proceso')], default='Pendiente', max_length=10),
        ),
    ]
