# Generated by Django 5.1 on 2024-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0031_alter_actageneral_acta_alter_invcientifica_investado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actageneral',
            name='acta',
            field=models.CharField(max_length=30),
        ),
    ]
