# Generated by Django 5.1 on 2024-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0032_alter_actageneral_acta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actageneral',
            name='acta',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
