# Generated by Django 5.1 on 2024-10-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0033_alter_actageneral_acta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actageneral',
            name='resultado',
            field=models.CharField(choices=[('Suficiente', 'Suficiente'), ('Insuficiente', 'Insuficiente')], default='Suficiente', max_length=15),
        ),
        migrations.CreateModel(
            name='ActaViaDiplomado',
            fields=[
                ('actageneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seg_mod_graduacion.actageneral')),
                ('valor_1', models.IntegerField()),
                ('valor_2', models.IntegerField()),
                ('valor_3', models.IntegerField()),
                ('totalnota', models.IntegerField()),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_presidente', to=settings.AUTH_USER_MODEL)),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_secretario', to=settings.AUTH_USER_MODEL)),
                ('vocal_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_vocal_1', to=settings.AUTH_USER_MODEL)),
                ('vocal_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_vocal_2', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('seg_mod_graduacion.actageneral',),
        ),
    ]
