# Generated by Django 5.1 on 2024-10-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg_mod_graduacion', '0034_alter_actageneral_resultado_actaviadiplomado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actageneral',
            name='estudiante_dos',
        ),
    ]
