# Generated by Django 5.1 on 2024-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/firmas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/users'),
        ),
    ]
