# Generated by Django 5.1 on 2024-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_user_firma_alter_user_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/signatures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/upload'),
        ),
    ]
