# Generated by Django 5.1 on 2024-10-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_alter_user_firma_alter_user_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firma',
        ),
    ]
