# Generated by Django 5.1 on 2024-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_remove_user_ci_remove_user_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Ru',
        ),
        migrations.AddField(
            model_name='user',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
