# Generated by Django 5.1 on 2024-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaccion_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_proyectos_iiisp',
            name='S_Descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='t_proyectos_iiisp',
            name='S_Documentacion',
            field=models.FileField(null=True, upload_to='Documento/', verbose_name='Documentación'),
        ),
        migrations.AlterField(
            model_name='t_proyectos_iiisp',
            name='S_Titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
    ]
