# Generated by Django 5.1 on 2024-10-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaccion_social', '0002_alter_t_proyectos_iiisp_s_descripcion_and_more'),
        ('seg_mod_graduacion', '0026_alter_comentarioprofinal_actdocorregido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_proyectos_iiisp',
            name='T_Gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.gestion', verbose_name='Gestion'),
        ),
        migrations.AlterField(
            model_name='t_proyectos_iiisp',
            name='T_Materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.materia', verbose_name='Materia'),
        ),
    ]
