# Generated by Django 5.1 on 2024-10-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaccion_social', '0003_alter_t_proyectos_iiisp_t_gestion_and_more'),
        ('seg_mod_graduacion', '0026_alter_comentarioprofinal_actdocorregido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_proyectos_iiisp',
            name='T_Gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg_mod_graduacion.periodo', verbose_name='Gestion'),
        ),
    ]
